name: lazy_page_view
description: A flutter package to create efficient, lazy loaded, uncertain length page views.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: