name: lazy_pageview
description: A flutter package to create efficient, lazy loaded, dynamically sized PageViews.
version: 0.0.2
homepage:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: